## Basic Usuage

### Importing Pandas
To import the pandas on any python projects, use `import pandas` command. After the import, we simply can check the pandas version installed using the command `pandas.__version__`.

In [1]:
import pandas

In [2]:
pandas.__version__

'2.3.3'

In [3]:
import pandas as pd

In [4]:
pd.__version__

'2.3.3'

### Creating Pandas Series

#### Using NumPy Arrays

##### Creating Series without index from array

In [5]:
import numpy as np

In [7]:
array_a =  np.array(["I", "Love", "Python"])

In [8]:
series_from_array = pd.Series(array_a)
series_from_array

0         I
1      Love
2    Python
dtype: object

In [9]:
type(series_from_array)

pandas.core.series.Series

In [10]:
series_from_array[2]

'Python'

##### Creating Series with Index from array

In [11]:
series_from_array_index = pd.Series(array_a, index=['a', 'b', 'c'])
series_from_array_index

a         I
b      Love
c    Python
dtype: object

In [12]:
series_from_array_index['c']

'Python'

*Note: Series can be created from Python List similar to the above by passing the list as an argument to `pd.Series()`.*

#### Using Python Dictionary

In [13]:
dict_a = {'Ram':90, 'Hari':86.5, 'Gita':87.3}

In [14]:
series_from_dict = pd.Series(dict_a)
series_from_dict

Ram     90.0
Hari    86.5
Gita    87.3
dtype: float64

In [15]:
series_from_dict.index

Index(['Ram', 'Hari', 'Gita'], dtype='object')

In [16]:
series_from_dict.values

array([90. , 86.5, 87.3])

### Creating Python DataFrames

#### Using Python List

In [19]:
list_a = ['Python', 'Ruby','Rust','Java','PHP']

In [20]:
dataframe_from_list = pd.DataFrame(list_a)

In [21]:
dataframe_from_list

        0
0  Python
1    Ruby
2    Rust
3    Java
4     PHP

##### *to create a column name, use the following*

In [24]:
dataframe_from_list_col_name = pd.DataFrame(list_a, columns=["Programming Languages"])
dataframe_from_list_col_name

  Programming Languages
0                Python
1                  Ruby
2                  Rust
3                  Java
4                   PHP

In [28]:
dataframe_from_list_col_name["Programming Languages"][2]

'Rust'

In [32]:
dataframe_from_list_col_name["Programming Languages"].iloc[2] # iloc -> integer location

'Rust'

##### Creating DataFrame from List of list

In [34]:
list_b = [["Ram Thapa", "Koteshwor"],["Nitesh Rai", "London"]]

In [35]:
data_frame = pd.DataFrame(list_b, columns=["Name", "Address"])

In [36]:
data_frame

         Name    Address
0   Ram Thapa  Koteshwor
1  Nitesh Rai     London

##### Creating DataFrame from List of list

In [37]:
dict_b = {"Name": ["Rita Thapa", "Nitesh Jung Kuwar"], "Address":["kalanki", "surkhet"]}

In [40]:
data_frames_from_dict = pd.DataFrame(dict_b)
data_frames_from_dict

                Name  Address
0         Rita Thapa  kalanki
1  Nitesh Jung Kuwar  surkhet

In [41]:
# create a row label
dataframe_from_dict_lables = pd.DataFrame(dict_b, index=["A", "B"])

In [42]:
dataframe_from_dict_lables

                Name  Address
A         Rita Thapa  kalanki
B  Nitesh Jung Kuwar  surkhet

### Indexing and Slicing Pandas Series

#### Indexing by Item name

In [43]:
series_from_array_index

a         I
b      Love
c    Python
dtype: object

In [44]:
series_from_array_index['a']

'I'

In [46]:
series_from_array_index['a':'c']

a         I
b      Love
c    Python
dtype: object

#### Indexing by number (Positional value)

In [47]:
series_from_array_index[0]

C:\Users\victus\AppData\Local\Temp\ipykernel_10520\246369587.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  series_from_array_index[0]

'I'

In [48]:
series_from_array_index[0:2]

a       I
b    Love
dtype: object