## Basic Usuage

### Importing Pandas
To import the pandas on any python projects, use `import pandas` command. After the import, we simply can check the pandas version installed using the command `pandas.__version__`.

In [1]:
import pandas

In [2]:
pandas.__version__

'2.3.3'

In [2]:
import pandas as pd

In [4]:
pd.__version__

'2.3.3'

### Creating Pandas Series

#### Using NumPy Arrays

##### Creating Series without index from array

In [5]:
import numpy as np

In [7]:
array_a =  np.array(["I", "Love", "Python"])

In [8]:
series_from_array = pd.Series(array_a)
series_from_array

0         I
1      Love
2    Python
dtype: object

In [9]:
type(series_from_array)

pandas.core.series.Series

In [10]:
series_from_array[2]

'Python'

##### Creating Series with Index from array

In [11]:
series_from_array_index = pd.Series(array_a, index=['a', 'b', 'c'])
series_from_array_index

a         I
b      Love
c    Python
dtype: object

In [12]:
series_from_array_index['c']

'Python'

*Note: Series can be created from Python List similar to the above by passing the list as an argument to `pd.Series()`.*

#### Using Python Dictionary

In [13]:
dict_a = {'Ram':90, 'Hari':86.5, 'Gita':87.3}

In [14]:
series_from_dict = pd.Series(dict_a)
series_from_dict

Ram     90.0
Hari    86.5
Gita    87.3
dtype: float64

In [15]:
series_from_dict.index

Index(['Ram', 'Hari', 'Gita'], dtype='object')

In [16]:
series_from_dict.values

array([90. , 86.5, 87.3])

### Creating Python DataFrames

#### Using Python List

In [19]:
list_a = ['Python', 'Ruby','Rust','Java','PHP']

In [20]:
dataframe_from_list = pd.DataFrame(list_a)

In [21]:
dataframe_from_list

        0
0  Python
1    Ruby
2    Rust
3    Java
4     PHP

##### *to create a column name, use the following*

In [24]:
dataframe_from_list_col_name = pd.DataFrame(list_a, columns=["Programming Languages"])
dataframe_from_list_col_name

  Programming Languages
0                Python
1                  Ruby
2                  Rust
3                  Java
4                   PHP

In [28]:
dataframe_from_list_col_name["Programming Languages"][2]

'Rust'

In [32]:
dataframe_from_list_col_name["Programming Languages"].iloc[2] # iloc -> integer location

'Rust'

##### Creating DataFrame from List of list

In [34]:
list_b = [["Ram Thapa", "Koteshwor"],["Nitesh Rai", "London"]]

In [35]:
data_frame = pd.DataFrame(list_b, columns=["Name", "Address"])

In [36]:
data_frame

         Name    Address
0   Ram Thapa  Koteshwor
1  Nitesh Rai     London

##### Creating DataFrame from List of list

In [37]:
dict_b = {"Name": ["Rita Thapa", "Nitesh Jung Kuwar"], "Address":["kalanki", "surkhet"]}

In [40]:
data_frames_from_dict = pd.DataFrame(dict_b)
data_frames_from_dict

                Name  Address
0         Rita Thapa  kalanki
1  Nitesh Jung Kuwar  surkhet

In [41]:
# create a row label
dataframe_from_dict_lables = pd.DataFrame(dict_b, index=["A", "B"])

In [42]:
dataframe_from_dict_lables

                Name  Address
A         Rita Thapa  kalanki
B  Nitesh Jung Kuwar  surkhet

### Indexing and Slicing Pandas Series

#### Indexing by Item name

In [43]:
series_from_array_index

a         I
b      Love
c    Python
dtype: object

In [44]:
series_from_array_index['a']

'I'

In [46]:
series_from_array_index['a':'c']

a         I
b      Love
c    Python
dtype: object

#### Indexing by number (Positional value)

In [47]:
series_from_array_index[0]

C:\Users\victus\AppData\Local\Temp\ipykernel_10520\246369587.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  series_from_array_index[0]

'I'

In [48]:
series_from_array_index[0:2]

a       I
b    Love
dtype: object

### Reading a csv file in Pandas
https://www.kaggle.com/datasets/leiladana/titanic?resource=download

In [4]:
dataset = pd.read_csv("titanic_train.csv")

In [5]:
dataset.head(6)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q

In [6]:
dataset.index

RangeIndex(start=0, stop=891, step=1)

In [7]:
dataset.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [8]:
dataset.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [9]:
dataset.describe(include='object')

                           Name   Sex  Ticket    Cabin Embarked
count                       891   891     891      204      889
unique                      891     2     681      147        3
top     Braund, Mr. Owen Harris  male  347082  B96 B98        S
freq                          1   577       7        4      644

In [10]:
type(dataset['Age'])

pandas.core.series.Series

In [11]:
dataset['Age'].unique()

array([22.  , 38.  , 26.  , 35.  ,   nan, 54.  ,  2.  , 27.  , 14.  ,
        4.  , 58.  , 20.  , 39.  , 55.  , 31.  , 34.  , 15.  , 28.  ,
        8.  , 19.  , 40.  , 66.  , 42.  , 21.  , 18.  ,  3.  ,  7.  ,
       49.  , 29.  , 65.  , 28.5 ,  5.  , 11.  , 45.  , 17.  , 32.  ,
       16.  , 25.  ,  0.83, 30.  , 33.  , 23.  , 24.  , 46.  , 59.  ,
       71.  , 37.  , 47.  , 14.5 , 70.5 , 32.5 , 12.  ,  9.  , 36.5 ,
       51.  , 55.5 , 40.5 , 44.  ,  1.  , 61.  , 56.  , 50.  , 36.  ,
       45.5 , 20.5 , 62.  , 41.  , 52.  , 63.  , 23.5 ,  0.92, 43.  ,
       60.  , 10.  , 64.  , 13.  , 48.  ,  0.75, 53.  , 57.  , 80.  ,
       70.  , 24.5 ,  6.  ,  0.67, 30.5 ,  0.42, 34.5 , 74.  ])

In the above result, one of the entry in the **age** column in **nan** that specifies the entry is **not a number**. In Machine Learning, as we need to deal with calculations, those should be handled using appropriate mechanisms. Some of the ideas to deal with **nan** values in dataset are as follows:
- Drop rows or columns with missing values.
- Fill the missing values with constant or scalar values.
- Fill the missing values with aggregated values like mean, median and mode of the particular column. 
- Fill the missing value with previous or next value (forward or backward fill)

In [14]:
dataset.isna() # is not avaiable?

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,True,False
887,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,False,False,True,False,False,False,False,True,False
889,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,True,False

In [15]:
dataset.isnull()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,True,False
887,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,False,False,True,False,False,False,False,True,False
889,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,True,False

In [17]:
dataset['Age'].value_counts()

Age
24.00    30
22.00    27
18.00    26
19.00    25
28.00    25
         ..
36.50     1
55.50     1
0.92      1
23.50     1
74.00     1
Name: count, Length: 88, dtype: int64

In [18]:
dataset['Age'].value_counts(dropna=False)

Age
NaN      177
24.00     30
22.00     27
18.00     26
28.00     25
        ...
36.50      1
55.50      1
0.92       1
23.50      1
74.00      1
Name: count, Length: 89, dtype: int64

In [19]:
dataset.shape

(891, 12)

In [22]:
dataset.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object